<!--
//TODO:
//1) Inputs in text mode if value is null (for room_no, father name, permanent address, telephone) -- Done
//2) GuideName, GuideEmail, Email can always be changed in text mode -- Done
//3) email will be updated in login_info table too if changed-- Done
//4) guideemil is checked for a valid IITK Faculty -- Done
//5) guideemail will be removed from the form (future plan)
//6) guidename from dropdown (of the student's dept), guideemail will be updated automatically (future plan)
//7) guidename, guideemail, last university, last university state not visible to UG Students -- Done
//8) Check for SQL Injections -- Done
//9) All Inputs in Caps (emails in lower) at server end -- Done
//10) All Inputs in Caps (emails in lower) at client end -- Done
//11) last_univ from Drop Down -- Done
//12) State from Drop Down -- Done
//13) If student changes email, a notification should go to the instructors of the courses for which he is registered (future plan)
//14) Further, his mail id should be updated in the course alias (future plan)

//Note:
//1) Remove ChangeEmail.asp, ChangeGuideEmail.asp, ChangeGuideName.asp after copying this page as these files are no longer required.
-->
<html>
<head>
<link REL="stylesheet" TYPE="text/css" HREF="../MainFrame.css">
<!--opens up a new pop-up window with the specified url-->
<script LANGUAGE="JavaScript">
function popUp(url,windowName)
{
	var new_window
	new_window = window.open(url,windowName,"width=550,height=350,toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbar=1,scrollbars=0,resizable=1,copyhistory=0")
}
</script>
<meta http-equiv="pragma" content="no-cache">
<script>parent.menu.location.href="../menu.asp?xml=student/menu.xml";</script>
<script>
var popwindow
var popwindowwidth=600
var popwindowheight=550
var popwindowtop=20

var popwindowleft=-popwindowwidth-50
var marginright
var pagecenter


function showWindow(popwindowURL, popwindowName, multi) 
{
//	popwindow = window.open(popwindowURL, "popwindow", "toolbar=no,width="+popwindowwidth+",height="+popwindowheight+",top="+popwindowtop+",left="+(-popwindowwidth)+"");
	popwindowtop = popwindowtop*multi;
	popwindowwidth = popwindowwidth-(multi*20);
	popwindow = window.open(popwindowURL, popwindowName, "toolbar=no,width="+popwindowwidth+",height="+popwindowheight+",top="+popwindowtop+",left="+(-popwindowwidth)+"");
	if (document.all) {
		marginright = (screen.width+50)*multi;
	}
	if (document.layers) {
		marginright = (screen.width+50)*multi
	}
	pagecenter=Math.floor(marginright/2)-Math.floor(popwindowwidth/2)
}

function toggleEmail(Email)
{
	if(Email.checked)
	{
		//var answer=prompt("Enter your Email Address","someone@Somewhere.com");
		this.location.href="Default.asp?GetEmail=Y";
	}	
	else
		if(confirm("Are you sure you want to disable email notifications?"))
			 this.location.href="Default.asp?GetEmail=N";
		else
			Email.checked=true;
}		 

</script>


</head>

<body link="#004000" bgColor="#fdf5e6">
<!--during Pre-reg-->
<script> </script>

<!--during HSS
<script> showWindow('../Help/UGMessage.html'); window.open('Semester_temp.asp','CurrentSemesterTemplate', "toolbar=no,width=350,height=600,top=20,left=20");</script>
<body onLoad=" showWindow('../Help/HSSMessage.html'); ">  
<body onLoad=" showWindow('../Help/PGMessage.html'); ">
-->
<br><H3><CENTER> Welcome Mr. DEEPAK KUMAR GUPTA</H3>
	<form Id="PersonalInfoForm" ACTION="Default.asp" METHOD="POST">
  <table width="98%" cellspacing="1" cellpadding="1">
    <tr> 
      <td width="28%">Roll Number: </td>

      <td>
        Y6154
      </td>
    </tr>
    <tr> 
      <td>Programme : </td>
      <td>7</td>
    </tr>
    <tr> 
      <td>Department : </td>

      <td> CSE</td>
    </tr>
    
    <tr> 
      <td>Campus Address : </td>
      <td> 
        <SELECT id=SelectHall name=SelectHall><OPTION value=''></OPTION><OPTION value=1095 >1095</OPTION><OPTION value=4 >4</OPTION><OPTION value=6117 >6117</OPTION><OPTION value=8 >8</OPTION><OPTION value=A212 >A212</OPTION><OPTION value=ACES >ACES</OPTION><OPTION value=G115 >G115</OPTION><OPTION value=G117 >G117</OPTION><OPTION value=G118 >G118</OPTION><OPTION value=GH >GH</OPTION><OPTION value=GH1 >GH1</OPTION><OPTION value=I >I</OPTION><OPTION value=II >II</OPTION><OPTION value=III >III</OPTION><OPTION value=IITK >IITK</OPTION><OPTION value=IV >IV</OPTION><OPTION value=IX  SELECTED >IX</OPTION><OPTION value=N.RA >N.RA</OPTION><OPTION value=OTHE >OTHE</OPTION><OPTION value=SBRA >SBRA</OPTION><OPTION value=SCH >SCH</OPTION><OPTION value=T-VI >T-VI</OPTION><OPTION value=T4 >T4</OPTION><OPTION value=V >V</OPTION><OPTION value=VI >VI</OPTION><OPTION value=VII >VII</OPTION><OPTION value=VIII >VIII</OPTION></SELECT><br><br></td></tr><tr><td></td><td>Room No 
        <input type="text" size="4" maxlength="4" name="ROOM_NO" onChange="javascript: this.value = this.value.toUpperCase();" value="G102"> 
        
      </td>

    </tr>
    <tr> 
      <td>Guardian/Parent : </td>
      <td> 
        SHIV SHANKAR PRASAD SHAH
        <input type="hidden" name="FATH_NAME" value="SHIV SHANKAR PRASAD SHAH"> 
        
      </td>
    </tr>
    <tr> 
      <td>Permanent Address : </td>

      <td> 
        HIG-180, SHASHTRIPURAM COLONY</td></tr><tr><td>&nbsp;</td><td>GORAKHNATH</td></tr><tr><td>&nbsp;</td><td>GORAKHPUR-273015</td></tr><tr><td>&nbsp;</td><td>UP
    <input type="hidden" name="ADD_1" value="HIG-180, SHASHTRIPURAM COLONY">
    <input type="hidden" name="ADD_2" value="GORAKHNATH">
    <input type="hidden" name="ADD_3" value="GORAKHPUR-273015">
    <input type="hidden" name="ADD_4" value="UP">
    
    <tr> 
      <td>Telephone : </td>

      <td> 
        0551-2261082
        <input type="hidden" name="TEL" value="0551-2261082"> 
        
      </td>
    </tr>
    <tr> 
      <td>Email : </td>
      <td> 
        
        <input type="text" size="30" maxlength="30" name="EMAIL" onChange="javascript: this.value = this.value.toLowerCase();" value="deepakkg@iitk.ac.in"> 
      </td>
    </tr>

    
    <tr> 
      <td>Last University :</td>
      <td> 
        <SELECT id=Selectlast_univ name=Selectlast_univ OnChange=><OPTION value=''></OPTION><OPTION value='ACHARYA NAGARJUNA UNIVERISTY' >ACHARYA NAGARJUNA UNIVERISTY</OPTION><OPTION value='ADDIS' >ADDIS</OPTION><OPTION value='ADU' >ADU</OPTION><OPTION value='AGRA UNIV' >AGRA UNIV</OPTION><OPTION value='ALA' >ALA</OPTION><OPTION value='ALD UNIV' >ALD UNIV</OPTION><OPTION value='ALMORA' >ALMORA</OPTION><OPTION value='ALWAR UNIV' >ALWAR UNIV</OPTION><OPTION value='AMU' >AMU</OPTION><OPTION value='ANANTAPUR' >ANANTAPUR</OPTION><OPTION value='ANDHARA UNIV' >ANDHARA UNIV</OPTION><OPTION value='ANNA UNIV' >ANNA UNIV</OPTION><OPTION value='AU' >AU</OPTION><OPTION value='AURANGABAD UNIV' >AURANGABAD UNIV</OPTION><OPTION value='AURAT' >AURAT</OPTION><OPTION value='B.R. AMBEDKAR BIHAR UNI.' >B.R. AMBEDKAR BIHAR UNI.</OPTION><OPTION value='BAMU' >BAMU</OPTION><OPTION value='BANGALORE UNIV' >BANGALORE UNIV</OPTION><OPTION value='BAREILLY UNIV' >BAREILLY UNIV</OPTION><OPTION value='BARK' >BARK</OPTION><OPTION value='BARODA UNIV' >BARODA UNIV</OPTION><OPTION value='BCE, BHAGALPUR' >BCE, BHAGALPUR</OPTION><OPTION value='BE COLLEGE (D.U)' >BE COLLEGE (D.U)</OPTION><OPTION value='BEC' >BEC</OPTION><OPTION value='BELGAUM' >BELGAUM</OPTION><OPTION value='BENGAL' >BENGAL</OPTION><OPTION value='BENGAL ENGINEERING COLLEGE' >BENGAL ENGINEERING COLLEGE</OPTION><OPTION value='BHA. UNIV. COIMBATORE' >BHA. UNIV. COIMBATORE</OPTION><OPTION value='BHAGALPUR UNIV' >BHAGALPUR UNIV</OPTION><OPTION value='BHARA' >BHARA</OPTION><OPTION value='BHARATHI' >BHARATHI</OPTION><OPTION value='BHARATHIAR UNIVERSITY' >BHARATHIAR UNIVERSITY</OPTION><OPTION value='BHARATHIDASAN UNIVERSITY' >BHARATHIDASAN UNIVERSITY</OPTION><OPTION value='BHARATHIWASAN UNIVERSITY' >BHARATHIWASAN UNIVERSITY</OPTION><OPTION value='BHILAI INSTITUE OF TECHNOLOGY' >BHILAI INSTITUE OF TECHNOLOGY</OPTION><OPTION value='BHOPAL' >BHOPAL</OPTION><OPTION value='BHTIK' >BHTIK</OPTION><OPTION value='BHU' >BHU</OPTION><OPTION value='BHUBAN' >BHUBAN</OPTION><OPTION value='BIET, BUNDELKHAND' >BIET, BUNDELKHAND</OPTION><OPTION value='BIHAR' >BIHAR</OPTION><OPTION value='BIT RANCHI' >BIT RANCHI</OPTION><OPTION value='BIT, DURG' >BIT, DURG</OPTION><OPTION value='BIT, SINDRI' >BIT, SINDRI</OPTION><OPTION value='BITS' >BITS</OPTION><OPTION value='BITS' >BITS</OPTION><OPTION value='BITS' >BITS</OPTION><OPTION value='BITS' >BITS</OPTION><OPTION value='BITS, PILLANI' >BITS, PILLANI</OPTION><OPTION value='BOMB' >BOMB</OPTION><OPTION value='BPUT' >BPUT</OPTION><OPTION value='BRA' >BRA</OPTION><OPTION value='BU' >BU</OPTION><OPTION value='BU' >BU</OPTION><OPTION value='BUC' >BUC</OPTION><OPTION value='BUNDELKHAND UNIV' >BUNDELKHAND UNIV</OPTION><OPTION value='BURD' >BURD</OPTION><OPTION value='BURDEAN' >BURDEAN</OPTION><OPTION value='BURDWAN UNIV' >BURDWAN UNIV</OPTION><OPTION value='BURDWAN UNIV' >BURDWAN UNIV</OPTION><OPTION value='BUREC' >BUREC</OPTION><OPTION value='CALCUTTA UNIV' >CALCUTTA UNIV</OPTION><OPTION value='CALICUT UNIV' >CALICUT UNIV</OPTION><OPTION value='CBIT' >CBIT</OPTION><OPTION value='CCS' >CCS</OPTION><OPTION value='CCSU, MEERUT' >CCSU, MEERUT</OPTION><OPTION value='CH. CHARAN SINGH UNI. MEERUT' >CH. CHARAN SINGH UNI. MEERUT</OPTION><OPTION value='CHANDIGARH' >CHANDIGARH</OPTION><OPTION value='COCHIN' >COCHIN</OPTION><OPTION value='COCHIN UNIVERSITY OF TECH' >COCHIN UNIVERSITY OF TECH</OPTION><OPTION value='COIMBATORE UNIV' >COIMBATORE UNIV</OPTION><OPTION value='CSJM UNIV' >CSJM UNIV</OPTION><OPTION value='CUMMINS, PUNE' >CUMMINS, PUNE</OPTION><OPTION value='DAV INDORE' >DAV INDORE</OPTION><OPTION value='DAVV' >DAVV</OPTION><OPTION value='DCE, DELHI' >DCE, DELHI</OPTION><OPTION value='DDU, GORAKHPUR' >DDU, GORAKHPUR</OPTION><OPTION value='DEEMED' >DEEMED</OPTION><OPTION value='DEEMED' >DEEMED</OPTION><OPTION value='DEEMED' >DEEMED</OPTION><OPTION value='DEEMED' >DEEMED</OPTION><OPTION value='DELHI UNIV' >DELHI UNIV</OPTION><OPTION value='DHANBAD' >DHANBAD</OPTION><OPTION value='DR. B.A.M.U.' >DR. B.A.M.U.</OPTION><OPTION value='DR. BHIMRAO AMBEDKAR UNIVERSIT' >DR. BHIMRAO AMBEDKAR UNIVERSIT</OPTION><OPTION value='DR. BMU' >DR. BMU</OPTION><OPTION value='DR. M G R MEDICAL UNI. CHENNAI' >DR. M G R MEDICAL UNI. CHENNAI</OPTION><OPTION value='DR. R.M.L. AVADH UNIVERSITY' >DR. R.M.L. AVADH UNIVERSITY</OPTION><OPTION value='DR. RAM M.L. A. UNIVERISTY' >DR. RAM M.L. A. UNIVERISTY</OPTION><OPTION value='DR. RAM MANOHAR LOHIA AVADH' >DR. RAM MANOHAR LOHIA AVADH</OPTION><OPTION value='DU' >DU</OPTION><OPTION value='DURG' >DURG</OPTION><OPTION value='DURGAPUR UNIV' >DURGAPUR UNIV</OPTION><OPTION value='ENSAE' >ENSAE</OPTION><OPTION value='FAIZABAD UNIV' >FAIZABAD UNIV</OPTION><OPTION value='G.S. INST  OF TECH & SCI' >G.S. INST  OF TECH & SCI</OPTION><OPTION value='GARHWAL' >GARHWAL</OPTION><OPTION value='GAUHATI UNIV' >GAUHATI UNIV</OPTION><OPTION value='GBP ENGG COLLEGE,' >GBP ENGG COLLEGE,</OPTION><OPTION value='GBPEC GARHWAL' >GBPEC GARHWAL</OPTION><OPTION value='GBPU' >GBPU</OPTION><OPTION value='GBPUAT, PANTNAGAR' >GBPUAT, PANTNAGAR</OPTION><OPTION value='GBU' >GBU</OPTION><OPTION value='GCE, SALEM' >GCE, SALEM</OPTION><OPTION value='GEC, AURANGABAD' >GEC, AURANGABAD</OPTION><OPTION value='GGSIP UNIV' >GGSIP UNIV</OPTION><OPTION value='GOA UNIV' >GOA UNIV</OPTION><OPTION value='GORAKHPUR UNIV' >GORAKHPUR UNIV</OPTION><OPTION value='GOVT ENGG COLLEGE BILASPUR C.G' >GOVT ENGG COLLEGE BILASPUR C.G</OPTION><OPTION value='GOVT. ENGG. COL., RAIPUR' >GOVT. ENGG. COL., RAIPUR</OPTION><OPTION value='GOVT. OF COLL. OF ARCHITECTURE' >GOVT. OF COLL. OF ARCHITECTURE</OPTION><OPTION value='GUAHATI UNIV' >GUAHATI UNIV</OPTION><OPTION value='GUJARAT UNIV' >GUJARAT UNIV</OPTION><OPTION value='GULBARGA UNIVERSITY' >GULBARGA UNIVERSITY</OPTION><OPTION value='GULBURGA UNIVERSITY' >GULBURGA UNIVERSITY</OPTION><OPTION value='GURUNANK DEV UNI.' >GURUNANK DEV UNI.</OPTION><OPTION value='GUWA' >GUWA</OPTION><OPTION value='GWALIOR UNIV' >GWALIOR UNIV</OPTION><OPTION value='H N B GARHWAL UNIV' >H N B GARHWAL UNIV</OPTION><OPTION value='H.C.O' >H.C.O</OPTION><OPTION value='HAMIRPUR' >HAMIRPUR</OPTION><OPTION value='HAZARIBAGH' >HAZARIBAGH</OPTION><OPTION value='HAZARIBAGH' >HAZARIBAGH</OPTION><OPTION value='HBTI' >HBTI</OPTION><OPTION value='HP UNIV' >HP UNIV</OPTION><OPTION value='HSU' >HSU</OPTION><OPTION value='HYDERABAD' >HYDERABAD</OPTION><OPTION value='HYU' >HYU</OPTION><OPTION value='I.E.T, C.S.J.M UNIV. KANPUR' >I.E.T, C.S.J.M UNIV. KANPUR</OPTION><OPTION value='I.G.I OF TECH.' >I.G.I OF TECH.</OPTION><OPTION value='IAF DEFENCE' >IAF DEFENCE</OPTION><OPTION value='IET' >IET</OPTION><OPTION value='IIIT' >IIIT</OPTION><OPTION value='IIKG' >IIKG</OPTION><OPTION value='IISB' >IISB</OPTION><OPTION value='IISC BANGALORE' >IISC BANGALORE</OPTION><OPTION value='IITB' >IITB</OPTION><OPTION value='IITD' >IITD</OPTION><OPTION value='IITG' >IITG</OPTION><OPTION value='IITK' >IITK</OPTION><OPTION value='IITKG' >IITKG</OPTION><OPTION value='IITM' >IITM</OPTION><OPTION value='IITR' >IITR</OPTION><OPTION value='IMT, GHAZIABAD' >IMT, GHAZIABAD</OPTION><OPTION value='INDORE' >INDORE</OPTION><OPTION value='INDORE' >INDORE</OPTION><OPTION value='IRM' >IRM</OPTION><OPTION value='ISI' >ISI</OPTION><OPTION value='ISM' >ISM</OPTION><OPTION value='ISMD' >ISMD</OPTION><OPTION value='IT BHU' >IT BHU</OPTION><OPTION value='J.N. TECH. UNI. A.P.' >J.N. TECH. UNI. A.P.</OPTION><OPTION value='JABALPUR UNIV' >JABALPUR UNIV</OPTION><OPTION value='JADAVPUR UNIV' >JADAVPUR UNIV</OPTION><OPTION value='JAI NARAIN VYAS UNI. JODHPUR' >JAI NARAIN VYAS UNI. JODHPUR</OPTION><OPTION value='JAIPUR UNIV' >JAIPUR UNIV</OPTION><OPTION value='JALANDHAR UNIV' >JALANDHAR UNIV</OPTION><OPTION value='JALPAIGURI' >JALPAIGURI</OPTION><OPTION value='JAMIA HAMDARD UNI.' >JAMIA HAMDARD UNI.</OPTION><OPTION value='JAMIA MILLIA ISLAMIA' >JAMIA MILLIA ISLAMIA</OPTION><OPTION value='JAMMU' >JAMMU</OPTION><OPTION value='JAMSHEDPUR UNIV' >JAMSHEDPUR UNIV</OPTION><OPTION value='JATU' >JATU</OPTION><OPTION value='JAWAHAR SC. COLLEGE' >JAWAHAR SC. COLLEGE</OPTION><OPTION value='JHANSI UNIV' >JHANSI UNIV</OPTION><OPTION value='JIWAJI UNIVERSITY' >JIWAJI UNIVERSITY</OPTION><OPTION value='JIWAJI, GWALIOR' >JIWAJI, GWALIOR</OPTION><OPTION value='JK' >JK</OPTION><OPTION value='JNGU' >JNGU</OPTION><OPTION value='JNTU' >JNTU</OPTION><OPTION value='JNU' >JNU</OPTION><OPTION value='JNU UNIV. JODHPUR' >JNU UNIV. JODHPUR</OPTION><OPTION value='JNVU' >JNVU</OPTION><OPTION value='JODHPUR UNIV' >JODHPUR UNIV</OPTION><OPTION value='JOSHPUR' >JOSHPUR</OPTION><OPTION value='JUTU' >JUTU</OPTION><OPTION value='KAKAT' >KAKAT</OPTION><OPTION value='KAKATIY' >KAKATIY</OPTION><OPTION value='KALYANI' >KALYANI</OPTION><OPTION value='KALYANI UNIV' >KALYANI UNIV</OPTION><OPTION value='KAMAUN UNIV' >KAMAUN UNIV</OPTION><OPTION value='KAN' >KAN</OPTION><OPTION value='KANNUR UNIVERSITY' >KANNUR UNIVERSITY</OPTION><OPTION value='KARNATAKA UNIV' >KARNATAKA UNIV</OPTION><OPTION value='KERALA' >KERALA</OPTION><OPTION value='KHAR' >KHAR</OPTION><OPTION value='KHARAGPUR' >KHARAGPUR</OPTION><OPTION value='KNIT' >KNIT</OPTION><OPTION value='KNIT, SULTANPUR' >KNIT, SULTANPUR</OPTION><OPTION value='KNMIET, GHAZ' >KNMIET, GHAZ</OPTION><OPTION value='KOLKATA' >KOLKATA</OPTION><OPTION value='KONKAN GYANPEETH COLL.ENGG.' >KONKAN GYANPEETH COLL.ENGG.</OPTION><OPTION value='KOTTAYAM' >KOTTAYAM</OPTION><OPTION value='KREC' >KREC</OPTION><OPTION value='KREC, SURATHKAL' >KREC, SURATHKAL</OPTION><OPTION value='KUMAON UNIVERSITY' >KUMAON UNIVERSITY</OPTION><OPTION value='KURU' >KURU</OPTION><OPTION value='KURUKSHETRA UNIV' >KURUKSHETRA UNIV</OPTION><OPTION value='KUVEMPU UNIVERSITY' >KUVEMPU UNIVERSITY</OPTION><OPTION value='L.I.T,NAGPUR UNIVERSITY' >L.I.T,NAGPUR UNIVERSITY</OPTION><OPTION value='LUCKNOW UNIV' >LUCKNOW UNIV</OPTION><OPTION value='M.D.U.' >M.D.U.</OPTION><OPTION value='M.J.P.ROHILKHAND UNIVERSITY' >M.J.P.ROHILKHAND UNIVERSITY</OPTION><OPTION value='M.M.M. ENGG. COLLE. GORAKHPUR' >M.M.M. ENGG. COLLE. GORAKHPUR</OPTION><OPTION value='M.P.BOARD' >M.P.BOARD</OPTION><OPTION value='M.S. UNIVERSITY' >M.S. UNIVERSITY</OPTION><OPTION value='MACT' >MACT</OPTION><OPTION value='MACT' >MACT</OPTION><OPTION value='MAD' >MAD</OPTION><OPTION value='MADHYA PRADESH STATE' >MADHYA PRADESH STATE</OPTION><OPTION value='MADRAS' >MADRAS</OPTION><OPTION value='MADRAS UNIV' >MADRAS UNIV</OPTION><OPTION value='MADRAS UNIV' >MADRAS UNIV</OPTION><OPTION value='MADU' >MADU</OPTION><OPTION value='MADURAI' >MADURAI</OPTION><OPTION value='MAGADH UNI. BODH-GAYA' >MAGADH UNI. BODH-GAYA</OPTION><OPTION value='MAHARASHTRA UNIV' >MAHARASHTRA UNIV</OPTION><OPTION value='MAHATMA GANDHI UNIV' >MAHATMA GANDHI UNIV</OPTION><OPTION value='MAHATMA GANDHI UNIV' >MAHATMA GANDHI UNIV</OPTION><OPTION value='MANGL' >MANGL</OPTION><OPTION value='MANIPAL' >MANIPAL</OPTION><OPTION value='MARATH' >MARATH</OPTION><OPTION value='MBA ENGG. COLL. J.N.V.U' >MBA ENGG. COLL. J.N.V.U</OPTION><OPTION value='MBM COLLAGE OF ENGG. JODHPUR' >MBM COLLAGE OF ENGG. JODHPUR</OPTION><OPTION value='MDU, ROHTAK' >MDU, ROHTAK</OPTION><OPTION value='MEERUT UNIV' >MEERUT UNIV</OPTION><OPTION value='MIDNAPORE UNIV' >MIDNAPORE UNIV</OPTION><OPTION value='MIT, MUZAFFARPUR' >MIT, MUZAFFARPUR</OPTION><OPTION value='MITS' >MITS</OPTION><OPTION value='MKU' >MKU</OPTION><OPTION value='MMME COLLEGE' >MMME COLLEGE</OPTION><OPTION value='MNIT, JAIPUR' >MNIT, JAIPUR</OPTION><OPTION value='MNNIT' >MNNIT</OPTION><OPTION value='MORADABAD' >MORADABAD</OPTION><OPTION value='MPUA & TECH.' >MPUA & TECH.</OPTION><OPTION value='MREC' >MREC</OPTION><OPTION value='MSRIT' >MSRIT</OPTION><OPTION value='MUHS' >MUHS</OPTION><OPTION value='MUICT' >MUICT</OPTION><OPTION value='MUMBAI UNIV' >MUMBAI UNIV</OPTION><OPTION value='MUMBAI UNIVERSITY' >MUMBAI UNIVERSITY</OPTION><OPTION value='MUMBAI, S.P.C.E' >MUMBAI, S.P.C.E</OPTION><OPTION value='MUZAFFARPUR' >MUZAFFARPUR</OPTION><OPTION value='MVSR ENGG., COLLEGE' >MVSR ENGG., COLLEGE</OPTION><OPTION value='MYSORE' >MYSORE</OPTION><OPTION value='N.E.R.I.S.T.' >N.E.R.I.S.T.</OPTION><OPTION value='NADIAD' >NADIAD</OPTION><OPTION value='NAG' >NAG</OPTION><OPTION value='NAGARJUNA UNIVERSITY' >NAGARJUNA UNIVERSITY</OPTION><OPTION value='NAGPUR UNIVERSITY' >NAGPUR UNIVERSITY</OPTION><OPTION value='NAINITAL' >NAINITAL</OPTION><OPTION value='NARAYANA ENGG. COLL.' >NARAYANA ENGG. COLL.</OPTION><OPTION value='NAVAL COLLEGE OF ENGG.' >NAVAL COLLEGE OF ENGG.</OPTION><OPTION value='NCT, BHOPAL' >NCT, BHOPAL</OPTION><OPTION value='NIFFT' >NIFFT</OPTION><OPTION value='NIT BHOPAL' >NIT BHOPAL</OPTION><OPTION value='NIT CALICUT' >NIT CALICUT</OPTION><OPTION value='NIT DURGAPUR' >NIT DURGAPUR</OPTION><OPTION value='NIT HAMIRPUR' >NIT HAMIRPUR</OPTION><OPTION value='NIT JALANDHAR' >NIT JALANDHAR</OPTION><OPTION value='NIT JAMSHEDPUR' >NIT JAMSHEDPUR</OPTION><OPTION value='NIT KURUKSHETRA' >NIT KURUKSHETRA</OPTION><OPTION value='NIT ROURKELA' >NIT ROURKELA</OPTION><OPTION value='NIT SILCHAR' >NIT SILCHAR</OPTION><OPTION value='NIT SURAT' >NIT SURAT</OPTION><OPTION value='NIT TRICHY' >NIT TRICHY</OPTION><OPTION value='NIT WARANGAL' >NIT WARANGAL</OPTION><OPTION value='NITJ' >NITJ</OPTION><OPTION value='NITK SURATHKAL' >NITK SURATHKAL</OPTION><OPTION value='NORTH BENGAL UNIV' >NORTH BENGAL UNIV</OPTION><OPTION value='NORTH ORISSA UNIV' >NORTH ORISSA UNIV</OPTION><OPTION value='OOSC' >OOSC</OPTION><OPTION value='ORISSA UNIV' >ORISSA UNIV</OPTION><OPTION value='OSMANIA UNIV' >OSMANIA UNIV</OPTION><OPTION value='PADMASRI DR. B.V R I T' >PADMASRI DR. B.V R I T</OPTION><OPTION value='PAN' >PAN</OPTION><OPTION value='PANJAB UNIV./ PUNJAB ENGG' >PANJAB UNIV./ PUNJAB ENGG</OPTION><OPTION value='PANJAB UNIVERSITY' >PANJAB UNIVERSITY</OPTION><OPTION value='PATNA' >PATNA</OPTION><OPTION value='PAURI' >PAURI</OPTION><OPTION value='PILANI' >PILANI</OPTION><OPTION value='PILANI' >PILANI</OPTION><OPTION value='PILANI' >PILANI</OPTION><OPTION value='PONDICHERRY' >PONDICHERRY</OPTION><OPTION value='POU' >POU</OPTION><OPTION value='PRU' >PRU</OPTION><OPTION value='PSG TECH. BHARATHIAR UNIV' >PSG TECH. BHARATHIAR UNIV</OPTION><OPTION value='PSGCT' >PSGCT</OPTION><OPTION value='PT. RSS UNIVERSITY' >PT. RSS UNIVERSITY</OPTION><OPTION value='PTU, LDH' >PTU, LDH</OPTION><OPTION value='PTU, SHSLCIET' >PTU, SHSLCIET</OPTION><OPTION value='PUNE UNIV' >PUNE UNIV</OPTION><OPTION value='PUNE, COEP' >PUNE, COEP</OPTION><OPTION value='PUNJAB' >PUNJAB</OPTION><OPTION value='PUNJAB TECHNICAL UNIV' >PUNJAB TECHNICAL UNIV</OPTION><OPTION value='PURVA' >PURVA</OPTION><OPTION value='R.V.T.U' >R.V.T.U</OPTION><OPTION value='RACHI UNIV' >RACHI UNIV</OPTION><OPTION value='RAIPUR UNIV' >RAIPUR UNIV</OPTION><OPTION value='RAJASTHAN UNIV' >RAJASTHAN UNIV</OPTION><OPTION value='RAJASTHAN UNIV' >RAJASTHAN UNIV</OPTION><OPTION value='RAJIV GANDHI, BHOPAL' >RAJIV GANDHI, BHOPAL</OPTION><OPTION value='RAMTEK' >RAMTEK</OPTION><OPTION value='RANCHI UNIV' >RANCHI UNIV</OPTION><OPTION value='RANI DURGAVATI' >RANI DURGAVATI</OPTION><OPTION value='RC' >RC</OPTION><OPTION value='RDU' >RDU</OPTION><OPTION value='REC DURGAPUR' >REC DURGAPUR</OPTION><OPTION value='RGPV, BHOPAL' >RGPV, BHOPAL</OPTION><OPTION value='RGUHS (KARNATAKA)' >RGUHS (KARNATAKA)</OPTION><OPTION value='RIT JAMSHEDPUR' >RIT JAMSHEDPUR</OPTION><OPTION value='RIT RAIPUR' >RIT RAIPUR</OPTION><OPTION value='RKE' >RKE</OPTION><OPTION value='RKE' >RKE</OPTION><OPTION value='RKE' >RKE</OPTION><OPTION value='ROHTAK' >ROHTAK</OPTION><OPTION value='ROHTAK' >ROHTAK</OPTION><OPTION value='ROORKEE UNIV' >ROORKEE UNIV</OPTION><OPTION value='ROR' >ROR</OPTION><OPTION value='ROR' >ROR</OPTION><OPTION value='ROURKELA' >ROURKELA</OPTION><OPTION value='RU' >RU</OPTION><OPTION value='RVR&JC, GUNTUR' >RVR&JC, GUNTUR</OPTION><OPTION value='S P UNIV' >S P UNIV</OPTION><OPTION value='S V UNIV' >S V UNIV</OPTION><OPTION value='SALEM' >SALEM</OPTION><OPTION value='SAMBALPUR UNIV' >SAMBALPUR UNIV</OPTION><OPTION value='SANGLI UNIV' >SANGLI UNIV</OPTION><OPTION value='SARDAR PATEL UNIVERSITY' >SARDAR PATEL UNIVERSITY</OPTION><OPTION value='SATHY' >SATHY</OPTION><OPTION value='SCH.OF PLAN. & ARCH.' >SCH.OF PLAN. & ARCH.</OPTION><OPTION value='SGSITS,' >SGSITS,</OPTION><OPTION value='SGU' >SGU</OPTION><OPTION value='SHIMLA' >SHIMLA</OPTION><OPTION value='SHIVAJI UNIVERSITY' >SHIVAJI UNIVERSITY</OPTION><OPTION value='SIDDHARTHA' >SIDDHARTHA</OPTION><OPTION value='SINDRI' >SINDRI</OPTION><OPTION value='SKD UNI' >SKD UNI</OPTION><OPTION value='SMIT' >SMIT</OPTION><OPTION value='SSJM' >SSJM</OPTION><OPTION value='SSSIHL' >SSSIHL</OPTION><OPTION value='SULTANPUR' >SULTANPUR</OPTION><OPTION value='SURAT' >SURAT</OPTION><OPTION value='SURATHKAL' >SURATHKAL</OPTION><OPTION value='SUSCET, MOHALI' >SUSCET, MOHALI</OPTION><OPTION value='SVNIT' >SVNIT</OPTION><OPTION value='SVU' >SVU</OPTION><OPTION value='THAPAR INST OF TECH' >THAPAR INST OF TECH</OPTION><OPTION value='TIRUCH' >TIRUCH</OPTION><OPTION value='TIRUPATHI' >TIRUPATHI</OPTION><OPTION value='TRIBHUVAN' >TRIBHUVAN</OPTION><OPTION value='TRICHY' >TRICHY</OPTION><OPTION value='TRIVANDRUM' >TRIVANDRUM</OPTION><OPTION value='UCE' >UCE</OPTION><OPTION value='UDCT' >UDCT</OPTION><OPTION value='UH' >UH</OPTION><OPTION value='UJJAIN' >UJJAIN</OPTION><OPTION value='UNIV COL OF ENGG' >UNIV COL OF ENGG</OPTION><OPTION value='UNIV COL OF ENGG BURLA' >UNIV COL OF ENGG BURLA</OPTION><OPTION value='UPTU' >UPTU</OPTION><OPTION value='UTKAL UNIV' >UTKAL UNIV</OPTION><OPTION value='VARANASI UNIV' >VARANASI UNIV</OPTION><OPTION value='VASAD' >VASAD</OPTION><OPTION value='VBU' >VBU</OPTION><OPTION value='VENKAT' >VENKAT</OPTION><OPTION value='VENKATESWARA' >VENKATESWARA</OPTION><OPTION value='VHNSN' >VHNSN</OPTION><OPTION value='VIDYASAGAR UNIV' >VIDYASAGAR UNIV</OPTION><OPTION value='VIKRAM UNIV' >VIKRAM UNIV</OPTION><OPTION value='VINOBA BHAVE UNIV' >VINOBA BHAVE UNIV</OPTION><OPTION value='VINOBA BHAVE UNIV' >VINOBA BHAVE UNIV</OPTION><OPTION value='VINOBA BHAVE UNIV' >VINOBA BHAVE UNIV</OPTION><OPTION value='VISHVESHWAIRAH' >VISHVESHWAIRAH</OPTION><OPTION value='VISV' >VISV</OPTION><OPTION value='VISVA BHARATI' >VISVA BHARATI</OPTION><OPTION value='VJTI, MUMBAI' >VJTI, MUMBAI</OPTION><OPTION value='VNIT' >VNIT</OPTION><OPTION value='VNIT' >VNIT</OPTION><OPTION value='VREC' >VREC</OPTION><OPTION value='VTU' >VTU</OPTION><OPTION value='W.B. UNIV.ANIM. & FISH. SEC.' >W.B. UNIV.ANIM. & FISH. SEC.</OPTION><OPTION value='WARANGAL UNIV' >WARANGAL UNIV</OPTION><OPTION value='WBUT' >WBUT</OPTION></SELECT><br><br>

      </td>
    </tr>
    <!--	
	<tr>
		<td>University State : (for PG Only)</td>
		<td>
		<SELECT id=Selectstate name=Selectstate><OPTION value=''></OPTION><OPTION value=AP>ACHARYA NAGARJUNA UNIVERISTY</OPTION><OPTION value=AP>ANDHARA PRADESH</OPTION><OPTION value=AP>ANDHRA PRADESH</OPTION><OPTION value=AP>BITS</OPTION><OPTION value=AP>CBIT</OPTION><OPTION value=AP>HYDERABAD, AP</OPTION><OPTION value=AP>HYU</OPTION><OPTION value=AP>JATU</OPTION><OPTION value=AP>JIWAJI, GWALIOR</OPTION><OPTION value=AP>JNGU</OPTION><OPTION value=AP>JUTU</OPTION><OPTION value=AP>KAKAT</OPTION><OPTION value=AP>KAKATIY</OPTION><OPTION value=AP>MVSR ENGG., COLLEGE</OPTION><OPTION value=AP>N.E.R.I.S.T.</OPTION><OPTION value=AP>OOSC</OPTION><OPTION value=AP>PADMASRI DR. B.V R I T</OPTION><OPTION value=AP>RVR&JC, GUNTUR</OPTION><OPTION value=AP>SIDDHARTHA</OPTION><OPTION value=AP>SKD UNI</OPTION><OPTION value=AP>SSSIHL</OPTION><OPTION value=AP>SVU</OPTION><OPTION value=AP>TIRUCH</OPTION><OPTION value=AP>TIRUPATHI</OPTION><OPTION value=AP>TRICHY</OPTION><OPTION value=AP>UH</OPTION><OPTION value=AP>VENKAT</OPTION><OPTION value=AP>WARANGAL, AP</OPTION><OPTION value=AS>GUWA</OPTION><OPTION value=ASSAM>ASSAM</OPTION><OPTION value=ASSAM>GUAHATI</OPTION><OPTION value=BANGALORE>R.V.T.U</OPTION><OPTION value=BH>RANCHI, BH</OPTION><OPTION value=BIH>MUZAFFARPUR</OPTION><OPTION value=BIHAR>BHAGALPUR</OPTION><OPTION value=BIHAR>BHAGALPUR, BIHAR</OPTION><OPTION value=BIHAR>BIHAR</OPTION><OPTION value=BIHAR>BITS</OPTION><OPTION value=BIHAR>BRA</OPTION><OPTION value=BIHAR>HAZARIBAGH</OPTION><OPTION value=BIHAR>ISMD</OPTION><OPTION value=BIHAR>JAMSHEDPUR</OPTION><OPTION value=BIHAR>MIT, MUZAFFARPUR</OPTION><OPTION value=BIHAR>NITJ</OPTION><OPTION value=BIHAR>PATNA</OPTION><OPTION value=BIHAR>RANCHI, BIHAR</OPTION><OPTION value=BIHAR>SINDRI</OPTION><OPTION value=C.T.>BIT, DURG</OPTION><OPTION value=CG>BHILAI INSTITUE OF TECHNOLOGY</OPTION><OPTION value=CG>CHHATISGARH</OPTION><OPTION value=CG>DURG</OPTION><OPTION value=CG>GOVT ENGG COLLEGE BILASPUR C.G</OPTION><OPTION value=CG>INDORE</OPTION><OPTION value=CG>MACT</OPTION><OPTION value=CG>PRU</OPTION><OPTION value=CG>RAIPUR, CG</OPTION><OPTION value=CHANDIGARH>CHANDIGARH</OPTION><OPTION value=CHANDIGARH>PTU, LDH</OPTION><OPTION value=CHANDIGARH>SUSCET, MOHALI</OPTION><OPTION value=DELHI>BE COLLEGE (D.U)</OPTION><OPTION value=DELHI>DELHI</OPTION><OPTION value=DELHI>GGSIPU</OPTION><OPTION value=DELHI>GHAZIABAD</OPTION><OPTION value=DELHI>I.G.I OF TECH.</OPTION><OPTION value=DELHI>JAMIA HAMDARD UNI.</OPTION><OPTION value=DELHI>MUHS</OPTION><OPTION value=DELHI>PILANI</OPTION><OPTION value=DELHI>ROHTAK</OPTION><OPTION value=DELHI>SCH.OF PLAN. & ARCH.</OPTION><OPTION value=DELHI>VBU</OPTION><OPTION value=ETHIOPIA>ADDIS</OPTION><OPTION value=GJ>M.S. UNIVERSITY</OPTION><OPTION value=GJ>SARDAR PATEL UNIVERSITY</OPTION><OPTION value=GOA>GOA</OPTION><OPTION value=GUJARAT>GUJARAT</OPTION><OPTION value=GUJARAT>NADIAD</OPTION><OPTION value=GUJARAT>PILANI</OPTION><OPTION value=GUJARAT>SURAT</OPTION><OPTION value=GUJARAT>VASAD</OPTION><OPTION value=HARYANA>HARYANA</OPTION><OPTION value=HARYANA>ROHTAK</OPTION><OPTION value=HARYANA>ROHTAK, HARYANA</OPTION><OPTION value=HP>HAMIRPUR, HP</OPTION><OPTION value=HP>HIMACHAL PRADESH</OPTION><OPTION value=HP>SHIMLA</OPTION><OPTION value=HR>HARAYANA</OPTION><OPTION value=HR>HARYANA</OPTION><OPTION value=HR>KURU</OPTION><OPTION value=HR>M.D.U.</OPTION><OPTION value=HR>NIT KURUKSHETRA</OPTION><OPTION value=IAF>IAF DEFENCE</OPTION><OPTION value=JD>NIFFT</OPTION><OPTION value=JH>DEEMED</OPTION><OPTION value=JH>HAZARIBAGH</OPTION><OPTION value=JH>JHARKHAND</OPTION><OPTION value=JH>RU</OPTION><OPTION value=JH>SINDRI, JH</OPTION><OPTION value=JK>JAMMU</OPTION><OPTION value=JK>JAMSHEDPUR, JK</OPTION><OPTION value=JK>JK</OPTION><OPTION value=KARNATAKA>BANGALORE</OPTION><OPTION value=KARNATAKA>BELGAUM</OPTION><OPTION value=KARNATAKA>DEEMED</OPTION><OPTION value=KARNATAKA>GOVT. ENGG. COL., RAIPUR</OPTION><OPTION value=KARNATAKA>GULBURGA UNIVERSITY</OPTION><OPTION value=KARNATAKA>KARNATAKA</OPTION><OPTION value=KARNATAKA>KUVEMPU UNIVERSITY</OPTION><OPTION value=KARNATAKA>MYSORE</OPTION><OPTION value=KE>BHARA</OPTION><OPTION value=KERALA>COCHIN</OPTION><OPTION value=KERALA>COCHIN UNIVERSITY OF TECH.</OPTION><OPTION value=KERALA>KERALA</OPTION><OPTION value=KERALA>TRIVANDRUM</OPTION><OPTION value=KL>BITS</OPTION><OPTION value=KN>GULBARGA UNIVERSITY</OPTION><OPTION value=KN>SURATHKAL</OPTION><OPTION value=KR>MANGL</OPTION><OPTION value=KR>MSRIT</OPTION><OPTION value=MAHARASHTRA>GEC, AURANGABAD</OPTION><OPTION value=MH>DR. B.A.M.U.</OPTION><OPTION value=MH>DR. BMU</OPTION><OPTION value=MH>MAHARASHTRA</OPTION><OPTION value=MH>MAHARASTRA</OPTION><OPTION value=MH>MARATH</OPTION><OPTION value=MH>NAG</OPTION><OPTION value=MH>NAVAL COLLEGE OF ENGG.</OPTION><OPTION value=MH>PUNE, MAHARASHTRA</OPTION><OPTION value=MH>UDCT</OPTION><OPTION value=MH>W.B. UNIV.ANIM. & FISH. SEC.</OPTION><OPTION value=MP>BHOPAL, MP</OPTION><OPTION value=MP>DAVV</OPTION><OPTION value=MP>GWALIOR, MP</OPTION><OPTION value=MP>IIKG</OPTION><OPTION value=MP>INDORE</OPTION><OPTION value=MP>INDORE, MP</OPTION><OPTION value=MP>JABALPUR, MP</OPTION><OPTION value=MP>L.I.T,NAGPUR UNIVERSITY</OPTION><OPTION value=MP>M.P.BOARD</OPTION><OPTION value=MP>MACT</OPTION><OPTION value=MP>MADHYA PRADESH</OPTION><OPTION value=MP>MITS</OPTION><OPTION value=MP>NCT, BHOPAL</OPTION><OPTION value=MP>RANI DURGAVATI</OPTION><OPTION value=MP>RDU</OPTION><OPTION value=MP>RKE</OPTION><OPTION value=MP>SGSITS,</OPTION><OPTION value=MP>SGU</OPTION><OPTION value=MP>UJJAIN, MP</OPTION><OPTION value=MS>MORADABAD</OPTION><OPTION value=MS>RAMTEK</OPTION><OPTION value=MT>BOMB</OPTION><OPTION value=MT>KHAR</OPTION><OPTION value=NEPAL>TRIBHUVAN</OPTION><OPTION value=OR>BPUT</OPTION><OPTION value=OR>BURLA, ORISSA</OPTION><OPTION value=OR>ORISSA</OPTION><OPTION value=OR>ORRISA</OPTION><OPTION value=OR>RC</OPTION><OPTION value=OR>SAMBALPUR, ORISSA</OPTION><OPTION value=ORISSA>KALYANI</OPTION><OPTION value=ORISSA>NORTH ORISSA UNIVERSITY</OPTION><OPTION value=ORISSA>UCE</OPTION><OPTION value=PONDICHERRY>PONDICHERRY</OPTION><OPTION value=PUNJAB>PATIALA, PUNJAB</OPTION><OPTION value=PUNJAB>PUNJAB</OPTION><OPTION value=PUNJAB>ROURKELA</OPTION><OPTION value=RAJ>ALWAR, RAJASTHAN</OPTION><OPTION value=RAJ>BITS, PILLANI</OPTION><OPTION value=RAJ>IET</OPTION><OPTION value=RAJ>JAIPUR, RAJASTHAN</OPTION><OPTION value=RAJ>JODHPUR, RAJASTHAN</OPTION><OPTION value=RAJ>RAJASTHAN</OPTION><OPTION value=RAJ>SANGLI, RAJASTHAN</OPTION><OPTION value=TAMILNADU>GCE, SALEM</OPTION><OPTION value=TN>BHARATHI</OPTION><OPTION value=TN>BHARATHIAR UNIVERSITY</OPTION><OPTION value=TN>BUC</OPTION><OPTION value=TN>CHENNAI,TN</OPTION><OPTION value=TN>COIMBATORE, TAMILNADU</OPTION><OPTION value=TN>COIMBATORE, TN</OPTION><OPTION value=TN>HSU</OPTION><OPTION value=TN>MAD</OPTION><OPTION value=TN>MKU</OPTION><OPTION value=TN>SALEM</OPTION><OPTION value=TN>SATHY</OPTION><OPTION value=TN>SMIT</OPTION><OPTION value=TN>TAMIL NADU</OPTION><OPTION value=TN>TAMILNADU</OPTION><OPTION value=TN>VENKATESWARA</OPTION><OPTION value=U.P.>BIET, BUNDELKHAND</OPTION><OPTION value=U.P.>CH. CHARAN SINGH UNI. MEERUT</OPTION><OPTION value=U.P.>GOVT. OF COLL. OF ARCHITECTURE</OPTION><OPTION value=U.P.>M.M.M. ENGG. COLLE. GORAKHPUR</OPTION><OPTION value=UA>GARHWAL, UA</OPTION><OPTION value=UA>NAINITAL, UA</OPTION><OPTION value=UA>PANTNAGAR, UTTARANCHAL</OPTION><OPTION value=UA>PAURI GARHWAL</OPTION><OPTION value=UA>UTTARANCHAL</OPTION><OPTION value=UP>AGRA, Up</OPTION><OPTION value=UP>ALA</OPTION><OPTION value=UP>ALD UNIV</OPTION><OPTION value=UP>ALIGARH, UP</OPTION><OPTION value=UP>ALMORA</OPTION><OPTION value=UP>AU</OPTION><OPTION value=UP>BAREILLY, UP</OPTION><OPTION value=UP>BHTIK</OPTION><OPTION value=UP>BITS</OPTION><OPTION value=UP>BU</OPTION><OPTION value=UP>CCS</OPTION><OPTION value=UP>DCE, DELHI</OPTION><OPTION value=UP>DHANBAD</OPTION><OPTION value=UP>DR. BHIMRAO AMBEDKAR UNIVERSIT</OPTION><OPTION value=UP>DR. R.M.L. AVADH UNIVERSITY</OPTION><OPTION value=UP>DR. RAM M.L. A. UNIVERISTY</OPTION><OPTION value=UP>DR. RAM MANOHAR LOHIA AVADH</OPTION><OPTION value=UP>DU</OPTION><OPTION value=UP>ENSAE</OPTION><OPTION value=UP>FAIZABAD, UP</OPTION><OPTION value=UP>GBPU</OPTION><OPTION value=UP>GBU</OPTION><OPTION value=UP>GORAKHPUR, UP</OPTION><OPTION value=UP>I.E.T, C.S.J.M UNIV. KANPUR</OPTION><OPTION value=UP>IIIT</OPTION><OPTION value=UP>IRM</OPTION><OPTION value=UP>ISM</OPTION><OPTION value=UP>IT BHU</OPTION><OPTION value=UP>JHANSI, UP</OPTION><OPTION value=UP>JOSHPUR</OPTION><OPTION value=UP>KAMAUN UNIVERSITY</OPTION><OPTION value=UP>KAN</OPTION><OPTION value=UP>KANPUR, UP</OPTION><OPTION value=UP>KNIT</OPTION><OPTION value=UP>KNMIET, GHAZ</OPTION><OPTION value=UP>LUCKNOW, UP</OPTION><OPTION value=UP>M.J.P.ROHILKHAND UNIVERSITY, BAREILLY</OPTION><OPTION value=UP>MADU</OPTION><OPTION value=UP>MEERU, UP</OPTION><OPTION value=UP>MEERUT,UP</OPTION><OPTION value=UP>MMME COLLEGE</OPTION><OPTION value=UP>PILANI</OPTION><OPTION value=UP>POU</OPTION><OPTION value=UP>PURVA</OPTION><OPTION value=UP>RGUHS (KARNATAKA)</OPTION><OPTION value=UP>RKE</OPTION><OPTION value=UP>ROR</OPTION><OPTION value=UP>SSJM</OPTION><OPTION value=UP>SULTANPUR</OPTION><OPTION value=UP>SULTANPUR ,UP</OPTION><OPTION value=UP>UTTAR PRADESH</OPTION><OPTION value=UP>VARANASI, UP</OPTION><OPTION value=UT>NAINITAL</OPTION><OPTION value=UT>ROR</OPTION><OPTION value=UT>UTTARANCHAL</OPTION><OPTION value=Ua>PAN</OPTION><OPTION value=WB>BEC</OPTION><OPTION value=WB>BU</OPTION><OPTION value=WB>BURD</OPTION><OPTION value=WB>BURDEAN</OPTION><OPTION value=WB>BUREC</OPTION><OPTION value=WB>DURGAPUR</OPTION><OPTION value=WB>IISB</OPTION><OPTION value=WB>ISI</OPTION><OPTION value=WB>JALPAIGURI</OPTION><OPTION value=WB>KHARAGPUR, WB</OPTION><OPTION value=WB>KOLKATA</OPTION><OPTION value=WB>MIDNAPORE, WB</OPTION><OPTION value=WB>RACHI</OPTION><OPTION value=WB>REC DURGAPUR</OPTION><OPTION value=WB>RKE</OPTION><OPTION value=WB>WEST BENGAL</OPTION></SELECT><br><br>
		</td>
	</tr>
-->
    <tr> 
      <td>1st Supervisor Email : </td>
      <td width="22%"> 
        
        <input type="text" size="30" maxlength="30" name="GUIDEEMAIL" onKeyUp="javascript: this.value = this.value.toLowerCase();" value=""> 
      </td>
      <td width="26%">1st Supervisor Name : </td>

      <td width="24%"> 
        
      </td>
    </tr>
    <tr> 
      <td>2nd Supervisor Email : </td>
      <td> 
        
        <input type="text" size="30" maxlength="30" name="GUIDEEMAIL2" onKeyUp="javascript: this.value = this.value.toLowerCase();" value=""> 
      </td>
      <td>2nd Supervisor Name : </td>
      <td> 
        
      </td>

    </tr>
    
    <tr> 
      <td>Registration for semester : </td>
      <td>7</td>
  </table>
  <br>
	
<!--	<input type="checkbox" id="checkEmail" name="checkEmail"  onClick="toggleEmail(this)" value="ON">    -->
	<input type="checkbox" id="checkEmail" name="checkEmail" >

	<b>Receive email notifications of your requests and/or form status.</b><p><br>
	</p>
	<input TYPE="submit" VALUE="Update Personal Information" id="submit" name="submit">	
	</form>

					
					
					
<p>&nbsp;</p>

</body>
</html>












